config/routes.rb
Rails.application.routes.draw do
 
 

  get 'muestra/principal'

  get 'muestra/segundo'

  get 'administration/index', to: 'administration#index', as: 'administration'
  get 'usershow/:id', to: 'usershows#show', as: 'usershow'
  get 'question/:id', to: 'questions#show', as: 'question'
  get 'usershow/articulos/:id', to: 'usershows#articulos', as: 'articulos_usershow'
  get 'download_pdf', to: "home#download_doc", as: 'download_contrato'
  get 'articles/photo/:id,:article', to: "articles#photo", as: 'photo_article'
  get 'search/create'
  devise_for :users
  resources :questions
  resources :comments
  resources :brands
  resources :phones
  resources :articles
  resources :advertisements
  resources :publications
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  
  include AASM

  has_attached_file   :foto1,
                      :default_url => '/assets/no-image.png',
                      :url => ":s3_domain_url",
                      :styles => { :normal => ["560x560>",:jpg], :mini => ["429x429>",:jpg],:peque => ["130x130>",:jpg]},
                      :default_style => :meddium,
                      :storage => :s3,
                      :path => "upload/Article/foto1/:file_id/:style/:filename"
  validates_attachment_content_type :foto1, content_type: /\Aimage\/.*\z/
  validates :foto1, attachment_presence: { message:  ": La primera foto es obligatoria"}

  has_attached_file   :foto2,
                      :default_url => '/assets/no-image.png',
                      :url => ":s3_domain_url",
                      :styles => { :normal => ["560x560>",:jpg], :mini => ["429x429>",:jpg],:peque => ["130x130>",:jpg]},
                      :default_style => :meddium,
                      :storage => :s3,
                      :path => "upload/Article/foto2/:file_id/:style/:filename"
  validates_attachment_content_type :foto2, content_type: /\Aimage\/.*\z/

  has_attached_file   :foto3,
                      :default_url => '/assets/no-image.png',
                      :url => ":s3_domain_url",
                      :styles => { :normal => ["560x560>",:jpg], :mini => ["429x429>",:jpg],:peque => ["130x130>",:jpg]},
                      :default_style => :meddium,
                      :storage => :s3,
                      :path => "upload/Article/foto3/:file_id/:style/:filename"
  validates_attachment_content_type :foto3, content_type: /\Aimage\/.*\z/

  has_attached_file   :foto4,
                      :default_url => '/assets/no-image.png',
                      :url => ":s3_domain_url",
                      :styles => { :normal => ["560x560>",:jpg], :mini => ["429x429>",:jpg],:peque => ["130x130>",:jpg]},
                      :default_style => :meddium,
                      :storage => :s3,
                      :path => "upload/Article/foto4/:file_id/:style/:filename"
  validates_attachment_content_type :foto4, content_type: /\Aimage\/.*\z/



  
  belongs_to :phone
  belongs_to :user
  belongs_to :brand
  has_many :publications
  has_many :questions
  
  #scope :publicados, ->{ where(state: "published") }
  scope :vendidos, ->{ where(vendido: "si") }
  #scope :ultimos, ->{ order("created_at DESC")}
  validates :caracteristicas, length: { maximum: 280, message:  ": Maximo 280 caracteres" }
  validates :comentario, length: { maximum: 280, message:  ": Maximo 280 caracteres" }
  validates :precio, presence: { message:  ": Precio no especficado"}
  validates :precio_minimo, presence: { message:  ": Precio minimo no especficado"}
  validates :estado_fisico, presence: { message:  ": Estado fisico no especficado"}
  validates :estado_funcional, presence: { message:  ": Estado funcional no especficado"}
  validates :ciudad, presence: { message:  ": Ciudad no especficada"}
  validates :comentario, presence: { message:  ": Comentario no especficado si no tienes, agrega simplemente 'Sin comentarios'"}
  validates :celular, presence: { message:  ": Telefono no especficado si no tienes, agrega simplemente 'No tengo telefono'"}
  validates :caracteristicas, presence: { message:  ": Caracteristicas del telefono no especficados"}
  validates :brand_id, presence: { message:  ": Especifica una marca"}
  validates :phone_id, presence: { message:  ": Especifica un telefono"}

  aasm(:priority) do
    state :normal, :initial => true
    state :activo1
    state :activo2
    state :activo3
    state :inavilitado
    event :activar1 do
       transitions :from => :normal, :to => :activo1
    end
    event :activar2 do
       transitions :from => :normal, :to => :activo2
    end
    event :activar3 do
       transitions :from => :normal, :to => :activo3
    end
    event :desactivar1 do
      transitions :from => :activo1, :to => :normal
    end
    event :desactivar2 do
      transitions :from => :activo2, :to => :normal
    end
    event :desactivar3 do
      transitions :from => :activo3, :to => :normal
    end
    event :inavilitar1 do
      transitions :from => :activo1, :to => :inavilitado
    end
    event :inavilitar2 do
      transitions :from => :activo2, :to => :inavilitado
    end
    event :inavilitar3 do
      transitions :from => :activo3, :to => :inavilitado
    end
    event :inavilitardesactivo do
      transitions :from => :normal, :to => :inavilitado
    end
  end

  aasm(:cambio) do
  	state :no, :initial => true
  	state :si
  	event :sicambio do
  		transitions :from => :no, :to => :si
  	end
  	event :nocambio do
  		transitions :from => :si, :to => :no
  	end
  end
  aasm(:caja) do
  	state :no, :initial => true
  	state :si
  	event :sicaja do
  		transitions :from => :no, :to => :si
  	end
  	event :nocaja do
  		transitions from: :si, to: :no
  	end
  end
  aasm(:garantia) do
  	state :no, :initial => true
  	state :si
  	event :sigarantia do
  		transitions :from => :no, :to => :si
  	end
  	event :nogarantia do
  		transitions from: :si, to: :no
  	end
  end 
  aasm(:factura) do
  	state :no, :initial => true
  	state :si
  	event :sifactura do
  		transitions :from => :no, :to => :si
  	end
  	event :nofactura do
  		transitions from: :si, to: :no
  	end
  end
  aasm(:audifonos) do
  	state :no, :initial => true
  	state :si
  	event :siaudifonos do
  		transitions :from => :no, :to => :si
  	end
  	event :noaudifonos do
  		transitions from: :si, to: :no
  	end
  end
  aasm(:cargador) do
  	state :no, :initial => true
  	state :si
  	event :sicargador do
  		transitions :from => :no, :to => :si
  	end
  	event :nocargador do
  		transitions from: :si, to: :no
  	end
  end
  
  aasm(:efectivo) do
  	state :no, :initial => true
  	state :si
  	event :siefectivo do
  		transitions :from => :no, :to => :si
  	end
  	event :noefectivo do
  		transitions from: :si, to: :no
  	end
  end
  aasm(:vidriotemplado) do
  	state :no, :initial => true
  	state :si
  	event :sividriotemplado do
  		transitions :from => :no, :to => :si
  	end
  	event :novidriotemplado do
  		transitions from: :si, to: :no
  	end
  end
  aasm(:funda) do
  	state :no, :initial => true
  	state :si
  	event :sifunda do
  		transitions :from => :no, :to => :si
  	end
  	event :nofunda do
  		transitions from: :si, to: :no
  	end
  end
  aasm(:vendido) do
  	state :no, :initial => true
  	state :si
  	event :sivendido do
  		transitions :from => :no, :to => :si
  	end
  	event :novendido do
  		transitions from: :si, to: :no
  	end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_normal_user!, except: [:show,:photo]

  def index
    @articles = Article.all
  end

  def show
  	@article = Article.find(params[:id])
    @question = Question.new
    @questions = @article.questions
    @cont = 0
    if !@article.foto1_file_name.nil?
      @cont += 1
    end
    if !@article.foto2_file_name.nil?
      @cont += 1
    end
    if !@article.foto3_file_name.nil?
      @cont += 1
    end
    if !@article.foto4_file_name.nil?
      @cont += 1
    end

    @calificaciones = [
      ["Malo","Malo","Malo","Regular","Regular","Regular","Bueno","Bueno","Excelente","Excelente"],
      ["Malo","Malo","Malo","Regular","Regular","Regular","Bueno","Bueno","Excelente","Excelente"]
    ]

  end

  def new
  	@article = Article.new
    @calificaciones = [
      ["Malo","Malo","Malo","Regular","Regular","Regular","Bueno","Bueno","Excelente","Excelente"],
      ["Malo","Malo","Malo","Regular","Regular","Regular","Bueno","Bueno","Excelente","Excelente"]
    ]
  end
  
  def create
    @article = current_user.articles.new(article_params)
    
    if @article.save 
      @publication = current_user.publications.new(:article_id => @article.id)
      if @publication.save
        redirect_to @article
      else
      render :new
      end
    else
      @calificaciones = [
        ["Malo","Malo","Malo","Regular","Regular","Regular","Bueno","Bueno","Excelente","Excelente"],
        ["Malo","Malo","Malo","Regular","Regular","Regular","Bueno","Bueno","Excelente","Excelente"]
      ]
      render :new
    end
  end

  def edit
    redirect_to root_path unless current_user.id == Article.find(params[:id]).user.id || current_user.is_admin_user?
    @article = Article.find(params[:id])
    
  end

  def update
    reset_check_box
    @article = Article.find(params[:id])
    if  @article.update(article_params)
      redirect_to  @article
    else
      render :edit
    end
  end
  def destroy
    @publication = Publication.find_by(article_id: params[:id])
    Publication.destroy(@publication.id)
    if Article.destroy(params[:id])
      redirect_to articles_path
    end 
  end
  def photo
    @article = Article.find(params[:article])
    if params[:id] == "1"
      @photo = @article.foto1.url(:original)
    elsif params[:id] == "2"
      @photo = @article.foto2.url(:original)
    elsif params[:id] == "3"
      @photo = @article.foto3.url(:original)
    elsif params[:id] == "4"
      @photo = @article.foto4.url(:original)
    end
  end
  

  private

  def article_params
    if user_signed_in? 
      if current_user.is_admin_user?
        params.require(:article).permit(:vendido,:brand_id, :phone_id, :precio, :precio_minimo, :estado_fisico, :estado_funcional, :caja, :garantia, :factura, :audifonos, :cargador, :vidriotemplado, :funda, :cambio, :efectivo, :comentario, :caracteristicas, :foto1, :foto2, :foto3, :foto4, :ciudad,:priority,:celular)
      else
       params.require(:article).permit(:vendido,:brand_id, :phone_id, :precio, :precio_minimo, :estado_fisico, :estado_funcional, :caja, :garantia, :factura, :audifonos, :cargador, :vidriotemplado, :funda, :cambio, :efectivo, :comentario, :caracteristicas, :foto1, :foto2, :foto3, :foto4, :ciudad,:celular)
      end
    end
    
  end
  def reset_priority
    article = Article.find(params[:id])
    
    if article.may_desactivar1?
      article.desactivar1!
    end
    if article.may_desactivar2?
      article.desactivar2!
    end
    if article.may_desactivar3?
      article.desactivar3!
    end
    if article.may_inavilitar1?
      article.inavilitar1!
    end
    if article.may_inavilitar2?
      article.inavilitar2!
    end
    if article.may_inavilitar3?
      article.inavilitar3!
    end
    if article.may_inavilitardesactivo?
      article.inavilitardesactivo!
    end
  end

  def reset_check_box 
    article = Article.find(params[:id])
    
    if article.may_nocaja?
      article.nocaja!
    end
    if article.may_nogarantia?
      article.nogarantia!
    end
    if article.may_nofactura?
      article.nofactura!
    end
    if article.may_noaudifonos?
      article.noaudifonos!
    end
    if article.may_nocargador?
      article.nocargador!
    end
    if article.may_nofactura?
      article.nofactura!
    end
    if article.may_nocambio?
      article.nocambio!
    end
    if article.may_noefectivo?
      article.noefectivo!
    end
    if article.may_novidriotemplado?
      article.novidriotemplado!
    end
    if article.may_nofunda?
      article.nofunda!
    end
    if article.may_novendido?
      article.novendido!
    end
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<hr class="linea">
<div class="top-space">
	
	<div class="row">
		<div class="col-xs-4 text-left letra-times-new-roman vertical">
			<%= link_to brand_path(article.brand.id), data: { turbolinks: false}  do %>
				<%= article.phone.name %>
			<%end%>
		</div>
		<div class="row col-xs-5 last-xs text-right letra-times-new-roman">
      <div class="col-xs-2">
        <% if article.user.photo_file_name.nil? %>
            <%= image_tag "new_perfil_mini.png", class: "circular"  %>
        <%else%>
            <%= image_tag article.user.photo.url(:mini), class: "circular" %>
        <%end%>
      </div>
      <div class="col-xs-10 vertical">
        <%= link_to article.user.name, usershow_path(article.user.id) %>
      </div>


		</div>
		<div class="col-xs-3 red letra-times-new-roman">
			<% if !article.may_sivendido? %>
				VENDIDO
			<%end%>
		</div>
	</div>
	<%= link_to article_path(article.id), data: { turbolinks: false}  do %>
		<div class="slides top-space  no-margin">
			<% if !article.foto1_file_name.nil? %>
				<%= image_tag article.foto1.url(:normal), class: "border-5"%>

			<%elsif !article.foto2_file_name.nil? %>
				<%= image_tag article.foto2.url(:normal), class: "border-5"%>

			<%elsif !article.foto3_file_name.nil? %>
				<%= image_tag article.foto3.url(:normal), class: "border-5"%>

			<%elsif !article.foto4_file_name.nil? %>
				<%= image_tag article.foto4.url(:normal), class: "border-5"%>
			<%end%>
		</div>
		<div class="row">
			<div class="col-xs-6 text-left letra-times-new-roman grey">
				<%= article.ciudad %>
			</div>
			<div class="col-xs-6 last-xs text-right letra-times-new-roman negrilla">
				Precio: <%= number_to_currency(article.precio, precision: 0)%>
			</div>
		</div>
		<div class="text-justify letra-lucida-grande">
			caracteristicas: 
			 <%= article.caracteristicas.truncate(410) %>
		</div>
	<% end %>
	<div class="row col-xs-12 no-margin no-padding">
		<h5 class="col-xs-12 no-margin">Comentarios:</h5>
		<div class="row  center-xs " >
			<% article.questions.each do |question|%>
		 		<div class="text-left col-xs-12 be-grey" style="border-radius: 15px; margin-top: 10px;">
		 			<% if question.user.photo_file_name.nil? %>
						<%= image_tag "new_perfil_mini.png", class: "circular", style: "margin-top: 5px;"  %>
					<%else%>
						<%= image_tag question.user.photo.url(:mini), class: "circular" %>
					<%end%>
		 			<%= question.user.name %>:
		 			<%= question.body.truncate(130)%>
		 			<hr class="punteada no-margin">
		 		</div>
			<%end%>
		</div>
	</div>
</div>

app/views/articles/index.html.erb
<%= @articles.inspect %>

app/views/articles/photo.html.erb
<div class="row center-xs top-space ">
	<%= link_to "Ver tamaño original",  "#{@photo}", class: "btn white be-blue margin-lateral" %>
	<%= link_to "Volver", article_path(@article.id), class: "btn white be-blue margin-lateral", data: { turbolinks: false} %>
</div>
<div class="slides top-space top-space" style="">
	<%= image_tag @photo %>
</div>

app/views/articles/show.html.erb
<%= render "articles/standar" %>
<div class="row top-space letra-lucida-grande">
	<div class="row col-xs-6 ">
		<div class="col-xs-12">
			<h2 class="no-margin letra-times-new-roman">
				<%= @article.phone.name%>
			</h2>
		</div>
		<div id="coverslidesfondo" class="col-xs-12" style="display: none;">
			<% if  !@article.foto1_file_name.nil? %>
				<%= link_to (image_tag @article.foto1.url(:mini))%>
			<%end%>
		</div>
		<div id="coverslides" class="col-xs-12 no-padding ">
			<div class="<%= 'slides' unless @cont == 1 %>">
				<% if  !@article.foto1_file_name.nil? %>
					<%= link_to (image_tag @article.foto1.url(:mini)), photo_article_path(1,@article.id), data: { turbolinks: false}%>
				<%end%>
				<% if  !@article.foto2_file_name.nil? %>
					<%= link_to (image_tag @article.foto2.url(:mini)), photo_article_path(2,@article.id), data: { turbolinks: false} %>
				<%end%>
				<% if  !@article.foto3_file_name.nil? %>
					<%= link_to (image_tag @article.foto3.url(:mini)), photo_article_path(3,@article.id), data: { turbolinks: false} %>
				<%end%>
				<% if  !@article.foto4_file_name.nil? %>
					<%= link_to (image_tag @article.foto4.url(:mini)), photo_article_path(4,@article.id), data: { turbolinks: false} %>
				<%end%>
			</div>
			<% if @cont > 1 %>
				<script >
					$(function(){
				      $(".slides").slidesjs({
				      	
				      });
				    });
				</script> 
			<%end%>
		</div>
		
		<div class="col-xs-12 field  text-justify border-5" >
			<h4 class="no-margin letra-times-new-roman">Caracteristicas del telefono: </h4>
			<%= @article.caracteristicas.truncate(280) %>
		</div>
		<div class="col-xs-12 field  text-justify border-5" >
			<h4 class="no-margin letra-times-new-roman">Comentarios del vendedor:</h4>
			<%= @article.comentario.truncate(280) %>
		</div>
	</div>
	<div class="row col-xs-6 no-padding be-small">
		<div class="col-xs-12">
			<div class="row col-xs-12 center-xs">
				<div class="row col-xs-11 text-left be-blue letra-times-new-roman" style="border-radius: 15px; font-size: 1.5em;">
					<div class="col-xs-2 last-xs" style="padding-top: 5px;">
						<% if  @article.user.photo_file_name.nil? %>
							<%= image_tag "new_perfil_mini.png", class: "circular" %>
						<%else%>
							<%= image_tag @article.user.photo.url(:mini), class: "circular" %>
						<%end%>
						
					</div>
					
					<%= link_to @article.user.name, usershow_path(@article.user.id),class: "col-xs-10", style: "padding-top: 5px;"%>
				</div>
			</div>
			<div class="row col-xs-12 top-space">
				<div class="col-xs-6">
					Precio: 
				</div>
				<div class="col-xs-6 ">
					<%= number_to_currency(@article.precio, precision: 0) %>
				</div>
			</div>
			<div class="row col-xs-12 top-space">
				<div class="col-xs-6">
					Precio minimo:
				</div>
				<div class="col-xs-6">
					<%= number_to_currency(@article.precio_minimo, precision: 0)  %>
				</div>
			</div>
			<div class="row col-xs-12 top-space">
				<div class="col-xs-6">
					Ciudad:
				</div>
				<div class="col-xs-6 ">
					<%= @article.ciudad %>
				</div>
			</div>
			<div class="row col-xs-12 top-space">
				<div class="col-xs-6">
					Telefono:
				</div>
				<div class="row col-xs-6">
					<%= image_tag "logo_whatsapp.png", class: "col-xs-2 no-padding-right" %>
					<p class="col-xs-10 no-margin no-padding-left"><%= @article.celular %></p> 
					
				</div>
			</div>
			<div class="row col-xs-12 top-space">
				<div class="col-xs-6">
					Estado fisico:
				</div>
				<div class="col-xs-6">
					
					<div id="myBtn" style= " color: blue !important; text-decoration: underline;"><%= @article.estado_fisico %> Ver estandar</div>
				</div>
			</div>
			<div class="row col-xs-12 top-space">
				<div class="col-xs-6">
					Estado funcional:
				</div>
				<div class="col-xs-6" >
					
					<div id="myBtn2" style= " color: blue !important; text-decoration: underline;"><%= @article.estado_funcional%> Ver estandar</div>
				</div>
			</div>
			<hr class="col-xs-12 linea">
			<div class="row col-xs-12">
				<h3 class="col-xs-12 no-margin letra-times-new-roman negrilla">Se entrega con</h3>
				
				<div class="col-xs-12 List-without-points top-space" >
					<ul class="row no-padding no-margin">
						<li class="col-xs-3 " style="padding-right: 0px;">
							<%if @article.may_sicaja? %>
								<%= image_tag "check.png" %>
							<%else%>
								<%= image_tag "checked.png" %>
							<%end%>
							Caja
						</li>
						<li class="col-xs-3 no-padding ">
							<%if @article.may_sifunda? %>
								<%= image_tag "check.png" %>
							<%else%>
								<%= image_tag "checked.png" %>
							<%end%>
							Funda
						</li>
						<li class="col-xs-3 no-padding ">
							<%if @article.may_sigarantia? %>
								<%= image_tag "check.png" %>
							<%else%>
								<%= image_tag "checked.png" %>
							<%end%>
							Garantia
						</li>
						<li class="col-xs-3" style="padding-right: 0px;">
							<%if @article.may_sifactura? %>
								<%= image_tag "check.png" %>
							<%else%>
								<%= image_tag "checked.png" %>
							<%end%>
							Factura
						</li>
					</ul>
				</div>
				
				<div class="col-xs-12 List-without-points no-padding top-space" >
					<ul class="row no-padding no-margin" style="padding-right: 0px;">
						<li class="col-xs-4 ">
							<%if @article.may_siaudifonos? %>
								<%= image_tag "check.png" %>
							<%else%>
								<%= image_tag "checked.png" %>
							<%end%>
							Audifonos
						</li>
						<li class="col-xs-3 no-padding">
							<%if @article.may_sicargador? %>
								<%= image_tag "check.png" %>
							<%else%>
								<%= image_tag "checked.png" %>
							<%end%>
							Cargador
						</li>
						<li class="col-xs-5 no-padding">
							<%if @article.may_sividriotemplado? %>
								<%= image_tag "check.png" %>
							<%else%>
								<%= image_tag "checked.png" %>
							<%end%>
							Vidrio templado
						</li>
						
					</ul>
				</div>
				<hr class="col-xs-12 linea">
				<h3 class="col-xs-12 no-margin  letra-times-new-roman negrilla">Formas de pago</h3>
				<div class="row col-xs-12 top-space" >
					<div class="col-xs-12 List-without-points ">
						<ul class="row no-padding no-margin">
							<li class="col-xs-6">
								<%if @article.may_sicambio? %>
									<%= image_tag "check.png" %>
								<%else%>
									<%= image_tag "checked.png" %>
								<%end%>
								Cambio
							</li>
							<li class="col-xs-6">
								<%if @article.may_siefectivo? %>
									<%= image_tag "check.png" %>
								<%else%>
									<%= image_tag "checked.png" %>
								<%end%>
								Efectivo
							</li>
						</ul>
					</div>
					
				</div>
				
			</div>
			<div class="row col-xs-12 contrato-font top-space" style="padding-left: 22em;">
				<div class="col-xs-12 "	style="margin-left: 5em;">
					<%= image_tag "Contrato.png" %>
				</div>
				<div class="col-xs-3">
					<%= image_tag "contrato.jpg" %>
				</div>
				<div class="col-xs-9 top-space">
					<%= link_to 'Contrato de compra y venta de Celular', download_contrato_path, style: " color: blue !important; text-decoration: underline;", data: { turbolinks: false} %>
				</div>
				<div class="col-xs-12">
					Con ese contrato podras legalizar la compra o venta del telrefono  
				</div>
					
			</div>
		</div>
	</div>
</div>

<div class="row border-5 top-space center-xs" style="display: none;">
	<div class="row col-xs-12 center-xs">
		<h1 class="col-xs-8 text-center be-black white no-margin ">
			Asesoria a la hora de comprar
		</h1>
	</div>
	<div class="row col-xs-10 top-space">
		<div class="col-xs-6  bottom-space">
			<%= image_tag "contrato.jpg" %>
			<%= link_to 'Contrato de compra y venta de Celular', download_contrato_path, style: " color: blue !important; text-decoration: underline;" %></br>
			Con ese contrato podras legalizar la compra o venta del teefono  	
		</div>
		<div class="col-xs-6 top-space bottom-space">
			Contactaos nosotros te asesoramos </br>
			telfono: 3125630214</br>
			email: XXX@gmail.com	
		</div>
	</div>
</div>
<div class="row top-space" >
	<div class="row col-xs-12  letra-times-new-roman">
			<div class="col-xs-12">
				<%= form_for(@question ) do |f| %>
					<% @question.errors.full_messages.each do |message| %>
						<div class="be-red  white top-space">
							<%= message %>
						</div>
					<%end%>
					<div class="row center-xs">
						<div class="row col-xs-10  border-5">
							<div class="row col-xs-12 center-xs ">
								<h2 class="col-xs-10 text-center no-margin" style="font-size: 1em;">
									< Has una pregunta >
								</h2>
							</div>
							<div class="col-xs-9">
								<div class=" text-left bottom-space", >
									<% if user_signed_in? %>
										<%= f.label :body, "Pregunta #{current_user.name}"  %><br />
									<%else%>

										<%= f.label :body, "Inicia sesion y pregunta "  %><br />
									<%end%>
									<%= f.text_area :body, size: "12x1", placeholder: "Comentario", class: "from-control"%>
								</div>
								<div class="field " style=" display: none", >
									<%= f.label :article_id %><br />
									<%= f.text_field :article_id, class: "from-control", value: @article.id %>
								</div>
							</div>
							<% if user_signed_in? %>
								<div class="col-xd-3  center-xs top-space ">
									<%= f.submit "Comentar", class: "btn white be-blue" %>
								</div>
							<%else%>
								<a id="myBtnlogin2" style="margin-left: 1em;" >
									<%= image_tag "Boton_de_iniciar_session.png", class: "vertical"  %>
								</a>
							<%end%>
						</div>
							
					</div>
				<%end%>
			</div>
	</div>
</div>
<h1 class="">Comentarios:</h1>
<div class="row border-2 center-xs ">
	<% @questions.each do |question|%>
 		<div class="text-left col-xs-11 top-space">
 			<% if question.user.photo_file_name.nil? %>
				<%= image_tag "new_perfil_mini.png", class: "circular"  %>
			<%else%>
				<%= image_tag question.user.photo.url(:mini), class: "circular" %>
			<%end%>
 			<%= question.user.name %>:
 			<%= question.body%>
 			<hr class="punteada no-margin">
 		</div>
	<%end%>
</div>
<% if user_signed_in? %>
    <% if current_user.id == @article.user.id || current_user.is_admin_user?%>
    	<div class="field row center-xs">
			<%= link_to "Eliminar", @article, method: :delete, class: "btn white be-blue top-space margin-lateral" %>
			<%= link_to "Editar", edit_article_path , class: "btn white be-blue top-space margin-lateral" %>
		</div>	
    <%end%>
<%end%>