config/routes.rb
Rails.application.routes.draw do
 
 

  get 'muestra/principal'

  get 'muestra/segundo'

  get 'administration/index', to: 'administration#index', as: 'administration'
  get 'usershow/:id', to: 'usershows#show', as: 'usershow'
  get 'question/:id', to: 'questions#show', as: 'question'
  get 'usershow/articulos/:id', to: 'usershows#articulos', as: 'articulos_usershow'
  get 'download_pdf', to: "home#download_doc", as: 'download_contrato'
  get 'articles/photo/:id,:article', to: "articles#photo", as: 'photo_article'
  get 'search/create'
  devise_for :users
  resources :questions
  resources :comments
  resources :brands
  resources :phones
  resources :articles
  resources :advertisements
  resources :publications
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/parcials/_advertisement.html.erb
<div class="row center-xs no-padding">
	<% @advertisementsprincipal.each do |advertisement| %>
		<div class="col-xs-12">
			<%= link_to advertisement.url do %>
			 	<div class="text-left  letra-lucida-grande">
			 		<div >
			 			<div class="letra-times-new-roman" style="font-size: 15px;">
							<%= image_tag advertisement.photo.url(:mini), class: "circular" %>
							<%= advertisement.name %>
						</div>
					 	<div class="">
							<%= image_tag advertisement.cover.url(:mini), class: "circular"  %>
						</div>
						<div class="letra-lucida-grande" style="font-size: 10px; overflow:hidden;">
							<%= advertisement.slogan %>
						</div>
						<div class=" letra-lucida-grande" style=" font-size: 10px; color: blue !important; text-decoration: underline; overflow:hidden;">
							<%= advertisement.url.truncate(25)  %>
						</div>
						<div class=" letra-lucida-grande text-justify" style="font-size: 10px;">
							<%= advertisement.body.truncate(90) %>
						</div>
			 		</div>
				</div>
			<%end%>
		</div>	
	<%end%>
</div>

app/views/parcials/_login.html.erb
<div id="logmodlogo" class="logmod" style="display: none;">
  <div class="logmod__wrapper">
    <span class="logmod__close">Close</span>
    <div class="logmod__container">
      <ul class="logmod__tabs">
        <li data-tabtar="lgm-2"><a href="#">Iniciar session</a></li>
        <li data-tabtar="lgm-1"><a href="#">Crear cuenta</a></li>
      </ul>
      <div class="logmod__tab-wrapper">
      <div class="logmod__tab lgm-1">
        <div class="logmod__heading">
          <span class="logmod__heading-subtitle">Ingresa tus datos <strong>para crear una cuenta</strong></span>
        </div>
        <div class="logmod__form">


          <%= form_for(User.new, as: "user", url: registration_path("user"), class: "simform") do |f| %>
            

            <div class="sminputs">
              <div class="input full">
              
                <%= f.label :name,"Nombre:", class: "string optional" %>
                <%= f.text_field :name, autofocus: true, placeholder: "Nombre", class: "from-control string optional", maxlength: "255" %>
              </div>
            </div>

            <div class="sminputs">
              <div class="input full">
                <%= f.label :email, class: "string optional" %>
                <%= f.email_field :email, autofocus: true, placeholder: "Email", class: "from-control string optional", maxlength: "255" %>
              </div>
            </div>
            
            <div class="sminputs">
              <div class="input string optional">

                <%= f.label :password, "Contraseña *", class: "string optional" %>
                <%= f.password_field :password, autocomplete: "off", class: "from-controlstring optional", maxlength: "255", size:"50", placeholder: "6 caracteres minimo"  %>
                
              </div>
              <div class="input string optional">

                <%= f.label :password_confirmation, "Confirma contraseña *", class: "string optional" %>
                <%= f.password_field :password_confirmation, autocomplete: "off", class: "from-control string optional", maxlength: "255", placeholder: "Confirmar contraseña", size:"50" %>
              </div>
            </div>
            <div class="simform__actions">
              <%= f.submit "Registrarse", class: "sumbit"%>
              <span class="simform__actions-sidetext">Al crear una cuenta acepta nuestros Términos y Privacidad <a class="special" href="#" target="_blank" role="link">Términos y Privacidad</a></span>
            </div> 
          <% end %>
        </div> 
      </div>
      <div class="logmod__tab lgm-2">
        <div class="logmod__heading">
          <span class="logmod__heading-subtitle">Ingresa tu email y contraseña <strong>para iniciar session</strong></span>
        </div> 
        <div class="logmod__form">
          <%= form_for(User.new, as: "user", url: session_path("user"), class: "simform") do |f| %>
            <div class="sminputs">
              <div class="input full">
                <%= f.label :email, "Email*", class: "string optional" %>
                <%= f.email_field :email, autofocus: true, placeholder: "Email", class: "from-control string optional", maxlength: "255", size:"50" %>
              </div>
            </div>
            <div class="sminputs">
              <div class="input full">
                <%= f.label :password, " Contraseña: ", class: "string optional"%>
                <%= f.password_field :password, autocomplete: "off",class: "from-control string optional", maxlength: "255", size:"50", placeholder: "Contraseña" %>
                            <span class="hide-password">Ver</span>
              </div>
            </div>
            <div class="simform__actions" >
              <%= f.submit "Ingresar", class: "sumbit"%>
              <span class="simform__actions-sidetext" style="display: none;">
                <a class="special" role="link" href="#">Forgot your password?<br>Click here</a>
              </span>
            </div> 
          <% end %>
        </div> 
          </div>
      </div>
    </div>
  </div>
</div>

app/views/parcials/_navigation_menu.html.erb
<header>
	
	<div class=" List-without-points letra-times-new-roman fondo-barra" style="font-size: 1.2em; " >
		
		<ul class="no-list row center-xs middle-xs no-margin">
			<li class="row col-xs">
				<%= link_to (image_tag "logo.png"), root_path, class: "col-xs-4 no-padding", data: { turbolinks: false}%>
				<%= link_to " Celuprecios", root_path,class: "col-xs-8 top-space no-padding text-left", data: { turbolinks: false} %>
			</li>
			<li class="col-xs">
				<%= link_to "Blogs","http://celuprecios.blogspot.com.co" %>
			</li>
			<li class="col-xs">
				<div class="box">
				  <div class="container-4">
				  	<%= form_tag "/search/create", method: :get, remote: true do %>
						<%= text_field_tag :keyword, nil, placeholder: "Que buscas"%>
						<%= content_tag :button, nil, type: :submit, class: "icon no-padding"  do %> 
							<i class="fa fa-search">
							<%= image_tag "http://icons.iconarchive.com/icons/custom-icon-design/mono-general-2/24/search-icon.png" %> 
							</i>
						<%end%>
					<%end%>
				    
				  </div>
				</div>

			</li>
			<% if user_signed_in? %>
				<li class="col-xs">
					<%= link_to "Mi perfil", usershow_path(current_user.id) %>
				</li>
				<li class="col-xs">
					<% if current_user.is_admin_user? %>
						<%= link_to "Panel de control", administration_path %>
					<% else %>
						<%= link_to "Vender +", new_article_path, data: { turbolinks: false} %>
					<%end%>
				</li>
				<li class="col-xs">
					<%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete %>
				</li>
			<% else %>
				<li class="col-xs">
					<a id="myBtnlogin3" >
					  Vender +
					</a>
				</li>
				<li class="col-xs">
					<a id="myBtnlogin" >
					  Iniciar sesion
					</a>
				</li>
				<li class="col-xs">
					<%= link_to "Crear cuenta", new_user_registration_path, data: { turbolinks: false} %>
				</li>
			<%end%>
		</ul>
		
	</div>
</header>