config/routes.rb
Rails.application.routes.draw do
 
 

  get 'muestra/principal'

  get 'muestra/segundo'

  get 'administration/index', to: 'administration#index', as: 'administration'
  get 'usershow/:id', to: 'usershows#show', as: 'usershow'
  get 'question/:id', to: 'questions#show', as: 'question'
  get 'usershow/articulos/:id', to: 'usershows#articulos', as: 'articulos_usershow'
  get 'download_pdf', to: "home#download_doc", as: 'download_contrato'
  get 'articles/photo/:id,:article', to: "articles#photo", as: 'photo_article'
  get 'search/create'
  devise_for :users
  resources :questions
  resources :comments
  resources :brands
  resources :phones
  resources :articles
  resources :advertisements
  resources :publications
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
	include AASM
	has_attached_file   :photo,
                        :default_url => '/assets/no-image.png',
                        :url => ":s3_domain_url",
                        :styles => { :normal => ["161x205>",:jpg], :mini => ["30x30!",:jpg]},
                        :default_style => :meddium,
                        :storage => :s3,
                        :path => "upload/Advertisement/photo/:file_id/:style/:filename"
  	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

    has_attached_file   :cover,
                        :default_url => '/assets/no-image.png',
                        :url => ":s3_domain_url",
                        :styles => { normal: "500x500>", mini: "130x130>"},
                        :default_style => :meddium,
                        :storage => :s3,
                        :path => "upload/Advertisement/cover/:file_id/:style/:filename"
  	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/

	
	has_many :publications

	aasm(:state) do
		state :desactivo, :initial => true
		state :activo1
		state :activo2
		state :activo3
		state :inavilitado
		event :activar1 do
			 transitions :from => :desactivo, :to => :activo1
		end
		event :activar2 do
			 transitions :from => :desactivo, :to => :activo2
		end
		event :activar3 do
			 transitions :from => :desactivo, :to => :activo3
		end
		event :desactivar1 do
			transitions :from => :activo1, :to => :desactivo
		end
		event :desactivar2 do
			transitions :from => :activo2, :to => :desactivo
		end
		event :desactivar3 do
			transitions :from => :activo3, :to => :desactivo
		end
		event :inavilitar1 do
			transitions :from => :activo1, :to => :inavilitado
		end
		event :inavilitar2 do
			transitions :from => :activo2, :to => :inavilitado
		end
		event :inavilitar3 do
			transitions :from => :activo3, :to => :inavilitado
		end
		event :inavilitardesactivo do
			transitions :from => :desactivo, :to => :inavilitado
		end
	end
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  before_action :authenticate_admin_user!, except: [:show]
  def index
  	@advertisements = Advertisement.all.paginate(page: params[:page],per_page: 5).reorder('name DESC')
  end                 

  def new
  	@advertisement = Advertisement.new
  end

  def show
  	@advertisement = Advertisement.find(params[:id])
  end

  def edit
    @advertisement = Advertisement.find(params[:id])
  end

  def update
    reset_check_box
    @advertisement = Advertisement.find(params[:id])
    if @advertisement.update(advertisement_params)
      redirect_to advertisements_path
    else
      render :edit
    end
  end
  def create
    @advertisement = Advertisement.new(advertisement_params)
    
    if @advertisement.save 
      @publication = current_user.publications.new(:advertisement_id => @advertisement.id)
      if @publication.save
        redirect_to @advertisement
      else
      render :new
      end
    else
      render :new
    end
  end
  def destroy
    @publication = Publication.find_by(advertisement_id: params[:id])
    Publication.destroy(@publication.id)
    if Advertisement.destroy(params[:id])
      redirect_to advertisements_path
    end 
  end

  private

  def advertisement_params
    params.require(:advertisement).permit(:name, :photo, :body, :direccion, :url, :telefono, :slogan, :ciudad, :cover,:state,:phone)
  end
  
  def reset_check_box 
    advertisement = Advertisement.find(params[:id])
    
    if advertisement.may_desactivar1?
      advertisement.desactivar1!
    end
    if advertisement.may_desactivar2?
      advertisement.desactivar2!
    end
    if advertisement.may_desactivar3?
      advertisement.desactivar3!
    end
    if advertisement.may_inavilitar1?
      advertisement.inavilitar1!
    end
    if advertisement.may_inavilitar2?
      advertisement.inavilitar2!
    end
    if advertisement.may_inavilitar3?
      advertisement.inavilitar3!
    end
    if advertisement.may_inavilitardesactivo?
      advertisement.inavilitardesactivo!
    end
  end

end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/views/advertisements/_advertisement.html.erb
<%= link_to advertisement_path(advertisement.id) do %>
 	<div class="row">
		<div class="col-xs-9 text-left letra-times-new-roman" style= "font-size: 20px;">
			<%= image_tag advertisement.photo.url(:mini), class: "circular" %>
			<%= advertisement.name  %>
		</div>
		<div class="col-xs-3 ">
			<h4 class="text-center no-margin grey algo">Blog</h4>
		</div>
	</div>
	<div class="text-justify letra-lucida-grande">
		Telefono: <%= advertisement.phone %> </br> 
		<%= advertisement.body.truncate(410) %>
	</div>
	<div class="slides top-space  no-margin">
		<%= image_tag advertisement.cover.url(:normal), class: "border-5" %>
	</div>
<%end%>

app/views/advertisements/edit.html.erb
<div style="width: 80%; margin: 0 auto;">
 	
	<h3 class="letra-times-new-roman text-center" style="font-size: 1.5em;"> Editar Anunicio </h3>
	<%= form_for(@advertisement) do |f| %>
		<% @advertisement.errors.full_messages.each do |message| %>
			<div class="be-red  white top-space">
				<%= message %>
			</div>
		<%end%>

		<div class="field", >
			<%= f.label :name, "Nombre de la empresa:" %><br />
			<%= f.text_field :name, class: "from-control"%>
		</div>
		<div class="field", >
			Foto actual de la empresa<br />
			<%= image_tag @advertisement.photo.url(:normal) %>
			<p></p>
			Reemplazar foto:  <%= f.file_field :photo %>
		</div>
		<div class="field", >
			<%= f.label :url, "Direccion web de la empresa:" %><br />
			<%= f.text_field :url, class: "from-control"%>
		</div>
		<div class="field", >
			<%= f.label :phone, "Telefono de la empresa:" %><br />
			<%= f.text_field :phone, class: "from-control"%>
		</div>
		<div class="field", >
			<%= f.label :ciudad, "Ciudad:" %><br />
			<%= f.text_field :ciudad, class: "from-control"%>
		</div>
		<div class="field", >
			<%= f.label :direccion, "Direccion fisica de la empresa:" %><br />
			<%= f.text_field :direccion, class: "from-control"%>
		</div>
		<div class="field">
			<%= select_tag(:"advertisement[state]", options_for_select([['Ninguna prioridad', "desactivo"],['Primera pagina', 'activo1'], ['Segunda pagina', 'activo2'],['Tercera pagina', 'activo3'],['DESACTIVAR PUBLICIDAD', 'inavilitado']], 'desactivo'))%>
		</div>
		<div class="field", >
			<%= image_tag @advertisement.cover.url(:normal) %>
			<p></p>
			Reemplazar Portada del anuncio: <%= f.file_field :cover%>
		</div>
		<div class="field", >
			<%= f.label :slogan, "Titulo o slogan del anuncio:" %><br />
			<%= f.text_field :slogan, class: "from-control"%>
		</div>
		<div class="field", >
			<%= f.label :body, "Descripcion del anuncio:" %><br />
			<%= f.text_area :body, size: "12x4", class: "from-control"%>
		</div>

		<div class="field">
			<%= link_to "Eliminar", @advertisement,class: "btn white be-blue", :method => :delete %>
			<%= f.submit "Guardar", class: "btn white be-blue" %>
		</div>
	<%end%>
</div>

app/views/advertisements/index.html.erb
<div style="width: 80%; margin: 0 auto;">
 	<div class="row center-xs">
 		<h3 class="letra-times-new-roman text-center " style="font-size: 1.5em;"> <%= link_to "Agregar Publicidad", new_advertisement_path,class: "cletra-times-new-roman btn " %> 
 		</h3>
 		<div class="col-xs-8 ">
			<%= render @advertisements %>
			<div class="field">
				<h3><%= will_paginate @publications %></h3> 
			</div>
		</div> 
 	</div>
 	
</div>

app/views/advertisements/new.html.erb
<div style="width: 80%; margin: 0 auto;">
 	
	<h3 class="letra-times-new-roman text-center" style="font-size: 1.5em;"> Nuevo Anunicio </h3>
	<%= form_for(@advertisement) do |f| %>
		<% @advertisement.errors.full_messages.each do |message| %>
			<div class="be-red  white top-space">
				<%= message %>
			</div>
		<%end%>

		<div class="field", >
			<%= f.label :name, "Nombre de la empresa:" %><br />
			<%= f.text_field :name, class: "from-control"%>
		</div>
		<div class="field", >
			Foto:  <%= f.file_field :photo %>
		</div>
		<div class="field", >
			<%= f.label :url, "Direccion web de la empresa:" %><br />
			<%= f.text_field :url, class: "from-control"%>
		</div>
		<div class="field", >
			<%= f.label :phone, "Telefono de la empresa:" %><br />
			<%= f.text_field :phone, class: "from-control"%>
		</div>
		<div class="field", >
			<%= f.label :ciudad, "Ciudad:" %><br />
			<%= f.text_field :ciudad, class: "from-control"%>
		</div>
		<div class="field", >
			<%= f.label :direccion, "Direccion fisica de la empresa:" %><br />
			<%= f.text_field :direccion, class: "from-control"%>
		</div>
		
		<div class="field", >
			Portada del anuncio:  <%= f.file_field :cover%>
		</div>
		<div class="field", >
			<%= f.label :slogan, "Titulo o slogan del anuncio:" %><br />
			<%= f.text_field :slogan, class: "from-control"%>
		</div>
		<div class="field">
			<%= select_tag(:"advertisement[state]", options_for_select([['Ninguna prioridad', "desactivo"],['Primera pagina', 'activo1'], ['Segunda pagina', 'activo2'],['Tercera pagina', 'activo3'],['DESACTIVAR PUBLICIDAD', 'inavilitado']], 'desactivo'))%>
		</div>
		<div class="field", >
			<%= f.label :body, "Descripcion del anuncio:" %><br />
			<%= f.text_area :body, size: "12x4", class: "from-control"%>
		</div>

		<div class="field">
			<%= f.submit "Guardar", class: "btn white be-blue" %>
		</div>
	<%end%>
</div>

app/views/advertisements/show.html.erb
<div style="width: 80%; margin: 0 auto;">
	<h3 class="letra-times-new-roman text-center" style="font-size: 1.5em;"> Anunicio </h3>
	<div class="row be-small ">
		<div class="row center-xs text-left">
			<div class="row col-xs-10">
				<div class="col-xs-4 be-small top-space">
					<div class="", >
						<h3 class="no-margin">
						<%= @advertisement.name%>
						</h3>
					</div>
					<div class="slides">
						<%= image_tag @advertisement.photo.url(:normal) %>
					</div>
				</div>
				<div class="row col-xs-8 top-space">
					<div class="col-xs-12 top-space">
						<h2 class="white be-black text-center no-margin">Datos de la empresa</h2>
					</div>
					
					<div class="col-xs-6">
						Direccion web:
					</div>
					<div class="col-xs-6">
						<%=link_to @advertisement.url.truncate(20),@advertisement.url, style: "color: blue !important; text-decoration: underline;" %>
					</div>
					<div class="col-xs-6">
						Ciudad:
					</div>
					<div class="col-xs-6">
						<%= @advertisement.ciudad %>
					</div>
					<div class="col-xs-6">
						Telefono:
					</div>
					<div class="col-xs-6">
						<%= @advertisement.phone %>
					</div>
					<div class="col-xs-6">
						Direccion fisica:
					</div>
					<div class="col-xs-6">
						<%= @advertisement.direccion %>
					</div>
					<div class="col-xs-6">
						Titulo o slogan:
					</div>
					<div class="col-xs-6">
						<%= @advertisement.slogan%>
					</div>
					<div class="col-xs-12 ">
						Descripcion del anuncio:
					</div>
					<div class="col-xs-12 text-justify">
						<%= @advertisement.body%>
					</div>	
				</div>
			</div>
		</div>
		

		<h1 class="col-xs-12"> PORTADA</h1>
		<div class="col-xs-12 slides">
			<%= image_tag @advertisement.cover.url(:normal), class: "border-5" %>
		</div>
	</div> 	
	
	
	<% if user_signed_in? && current_user.is_admin_user? %>
		<div class="field row center-xs">
			<div >
				<%= link_to "Eliminar", @advertisement, method: :delete, class: "btn white be-blue top-space margin-lateral" %>
				<%= link_to "Editar", edit_advertisement_path , class: "btn white be-blue top-space margin-lateral" %>
			</div>
		</div>	
	<%end%>
	
</div>