config/routes.rb
Rails.application.routes.draw do
 
 

  get 'muestra/principal'

  get 'muestra/segundo'

  get 'administration/index', to: 'administration#index', as: 'administration'
  get 'usershow/:id', to: 'usershows#show', as: 'usershow'
  get 'question/:id', to: 'questions#show', as: 'question'
  get 'usershow/articulos/:id', to: 'usershows#articulos', as: 'articulos_usershow'
  get 'download_pdf', to: "home#download_doc", as: 'download_contrato'
  get 'articles/photo/:id,:article', to: "articles#photo", as: 'photo_article'
  get 'search/create'
  devise_for :users
  resources :questions
  resources :comments
  resources :brands
  resources :phones
  resources :articles
  resources :advertisements
  resources :publications
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/brand.rb
class Brand < ApplicationRecord

	has_attached_file   :logo,
                        :default_url => '/assets/no-image.png',
                        :url => ":s3_domain_url",
                        :styles => { :normal => ["200x200>",:jpg], :mini => ["75x75>",:jpg]},
                        :default_style => :meddium,
                        :storage => :s3,
                        :path => "upload/Brand/logo/:file_id/:style/:filename"
	
  	validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/

    validates :name, presence: { message:  ": No tiene nombre" }, uniqueness: { message:  ": Marca ya existe", case_sensitive: false }
    
  	has_many :phones
  	has_many :articles
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :authenticate_admin_user!, except: [:show]
  
	def index
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)

    if @brand.save
        redirect_to @brand
    else
        render :new
    end

  end

  def show
    @brand_articles = Brand.find(params[:id]).articles.paginate(page: params[:page],per_page: 5).order("created_at DESC")
    @brand = Brand.find(params[:id])
  end

  def edit
    @brand = Brand.find(params[:id])
  end

  def update
    
    if Brand.find(params[:id]).update(brand_params)
      redirect_to brands_path
    else
      render :edit
    end
  end

  def destroy
    @phones = Phone.destroy_all(brand_id: params[:id])
    
    @brand = Brand.find(params[:id])
    if @brand.destroy
      redirect_to brands_path
    end
  end

  private

  def brand_params
    params.require(:brand).permit(:name,:logo)
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_brand.html.erb
<div class="row center-xs no-padding">
	<% @brands.each do |brand| %>
		<div class="col-xs-6 top-space vertical " style="padding-left: 0;" >
			<%= link_to image_tag(brand.logo.url(:mini)), brand, data: { turbolinks: false} %> 
		</div>
	<%end%>
</div>
	
	

app/views/brands/edit.html.erb
<%= form_for(@brand) do |f| %>
	<h3 class="letra-times-new-roman text-center" style="font-size: 1.5em;"> Editar Marca </h3>
	<% @brand.errors.full_messages.each do |message| %>
		<div class="be-red  white top-space">
			<%= message %>
		</div>
	<%end%>
	<div class="field", >
		<%= f.label :name, "Nombre:" %><br />
		<%= f.text_field :name, placeholder: "Nombre", class: "from-control"%>
	</div>
	<div class="field">
		Logo:  <%= f.file_field :logo%>
	</div>
	<div class="field">
		<%= link_to "Eliminar", @brand,class: "btn white be-blue", :method => :delete %>
		<%= f.submit "Guardar", class: "btn white be-blue", method: :put %>
	</div>
<%end%>

app/views/brands/index.html.erb
<div style="width: 80%; margin: 0 auto;">
	<div>
		<div class="row">
			<div class="col-md-12 top-space">
				<h3 class="letra-times-new-roman text-center" style="font-size: 1.5em;"> Edicion De Marcas </h3>
				
			</div>
			<%@brands.each do |brand|%>
				<div class="col-md-4 top-space vertical">
					<%= link_to (image_tag brand.logo.url(:normal)), edit_brand_path(brand.id)  %>
				</div>
			<%end%>
		</div>
		<div class= "center-xs top-space">
			<%= link_to "Agregar Marca", new_brand_path, class: "btn white be-blue" %>
		</div>
	</div>
</div>

app/views/brands/new.html.erb
<div style="width: 80%; margin: 0 auto;">
 	
	<h3 class="letra-times-new-roman text-center" style="font-size: 1.5em;"> Nueva Marca </h3>
	<%= form_for(@brand) do |f| %>
		<% @brand.errors.full_messages.each do |message| %>
			<div class="be-red  white top-space">
				<%= message %>
			</div>
		<%end%>
		<div class="field", >
			<%= f.label :name, "Nombre:" %><br />
			<%= f.text_field :name, placeholder: "Nombre", class: "from-control"%>
		</div>
		<div class="field">
			Logo:  <%= f.file_field :logo%>
		</div>
		<div class="field">
			<%= f.submit "Guardar", class: "btn white be-blue" %>
		</div>
	<%end%>
</div>

app/views/brands/show.html.erb
<div class="row center-xs  be-small">
	<div class="col-xs-10 ">
		<h3 class="letra-times-new-roman text-center" style="font-size: 1.5em;"> Articulos relacionados con <%= @brand.name %> </h3>
	</div>
	<div class="col-xs-8 ">
		<%= render @brand_articles %>
	</div> 
	<div class="field col-xs-12">
		<h3><%= will_paginate @brand_articles  %></h3> 
	</div>
</div>
